version = 0.1

[dev.deploy.parameters]
stack_name = "quantum-motion-data-platform"
resolve_s3 = true
s3_prefix = "quantum-motion-data-platform"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "GatewayStageName=\"live\" LogLevel=\"INFO\" EnvironmentName=\"dev\""
image_repositories = []

